<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\eng\pkg.props" />
	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net6.0;net7.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<NoWarn>IDE0130</NoWarn>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Fast.Diagnostics.Generator" Version="1.2.0-preview.60" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="FastBIRe"/>
	</ItemGroup>
</Project>
